[package]
name = "gallium"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = { version = "0.37", features = ["linked"] }

[dev-dependencies]
png = "0.17.10"